# Generated by Django 4.1.1 on 2022-09-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="class_app.file",
            ),
        ),
    ]
