# Generated by Django 4.1.1 on 2022-09-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_customuser_user"),
        ("class_app", "0002_alter_classroom_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="authentication.customuser",
            ),
        ),
    ]
