# Generated by Django 4.1.1 on 2022-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0003_alter_classroom_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="classroom", name="file",),
        migrations.AddField(
            model_name="classroom",
            name="files",
            field=models.ManyToManyField(related_name="classroom", to="class_app.file"),
        ),
    ]
