# Generated by Django 4.1.1 on 2022-09-25 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "authentication",
            "0002_customuser_remove_student_user_remove_teacher_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
